# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5c793b8728835d6e9876726a391140891939795c48203bb2100e2d771df1ad2e69dde5decac572266950560a399187a65c874a5c6d5ded3ba03c89cb3159d04

test:
  secret_key_base: 794107698aa74f9ba9c7e1fad0dfd99845c9d6cd2e151a6ce081038a340b17b091c42a335ea230d1b3f2f910718f463728b73c521651318314a5e5fbcd08b846

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
